name: bitcoin_cloud_mining
description: A Bitcoin cloud mining app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: ^11.3.0
  package_info_plus: ^8.3.0
  country_picker: ^2.0.19
  cupertino_icons: ^1.0.2
  provider: ^6.1.4
  uuid: ^4.3.3
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  workmanager: ^0.5.2
  google_mobile_ads: ^4.0.0
  google_fonts: ^6.1.0
  audioplayers: ^5.2.1
  url_launcher: ^6.2.2
  fluttertoast: ^8.2.4
  font_awesome_flutter: ^10.6.0
  percent_indicator: ^4.2.3
  csv: ^6.0.0
  intl: ^0.19.0
  google_sign_in: ^6.2.1
  local_auth: ^2.1.7
  confetti: ^0.8.0
  dio: ^5.4.0  # Using dio as primary HTTP client
  flutter_local_notifications: ^16.3.0
  flutter_markdown: ^0.7.6+2
  qr_flutter: ^4.1.0
  share_plus: ^7.2.1
  qr_code_scanner: ^1.0.1
  speech_to_text: ^7.0.0
  crypto: ^3.0.3
  flutter_secure_storage: ^9.0.0  # Keep current for security
  fl_chart: ^0.70.2
  flutter_animate: ^4.5.0
  socket_io_client: ^2.0.3+1
  timeago: ^3.5.0
  rxdart: ^0.28.0
  mailer: ^6.0.1
  window_manager: ^0.4.3
  flutter_isolate: ^2.0.4
  flutter_native_splash: ^2.3.10
  http: ^1.1.0
  battery_plus: ^5.0.3
  connectivity_plus: ^5.0.2  # Using connectivity_plus instead of connectivity as it's more maintained
  web: ^1.0.0
  battery: ^2.0.3
  shimmer: ^3.0.0
  app_links: ^6.4.0
  uni_links: ^0.5.1
  decimal: ^2.3.3
  clipboard: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  custom_lint: ^0.7.5

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/team_member1.png.webp
    - assets/images/team_member2.png.webp
    - assets/images/default_avatar.png.webp
   
    - assets/audio/coin_sound.mp3
    - assets/audio/reward_sound.mp3
    - assets/audio/error_sound.mp3
    - assets/audio/background.mp3
    - assets/audio/collect.mp3
    - assets/sounds/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700


