name: bitcoin_mining_admin
description: Admin panel for Bitcoin Cloud Mining application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  intl: ^0.19.0
  fl_chart: ^0.62.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  url_launcher: ^6.1.10
  flutter_secure_storage: ^8.0.0
  connectivity_plus: ^4.0.1
  package_info_plus: ^4.0.2
  flutter_local_notifications: ^14.1.1
  path_provider: ^2.0.15
  image_picker: ^0.8.7+5
  file_picker: ^5.3.0
  dio: ^5.1.2
  flutter_dotenv: ^5.0.2
  logger: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.19

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/splash_logo.png
    - assets/icons/app_icon.png
    - assets/icons/app_icon_foreground.png
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash_logo.png
  android: true
  ios: true 