// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTBr5z9vixdO9TzzKVGCUVP-G4BaaMAyo',
    appId: '1:486206486627:web:993fedd92937142473e056',
    messagingSenderId: '486206486627',
    projectId: 'bitcoin-cloud-mining-19fb5',
    authDomain: 'bitcoin-cloud-mining-19fb5.firebaseapp.com',
    storageBucket: 'bitcoin-cloud-mining-19fb5.firebasestorage.app',
    measurementId: 'G-LPLPZBE2YV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTBr5z9vixdO9TzzKVGCUVP-G4BaaMAyo',
    appId: '1:486206486627:android:993fedd92937142473e056',
    messagingSenderId: '486206486627',
    projectId: 'bitcoin-cloud-mining-19fb5',
    storageBucket: 'bitcoin-cloud-mining-19fb5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTBr5z9vixdO9TzzKVGCUVP-G4BaaMAyo',
    appId: '1:486206486627:ios:993fedd92937142473e056',
    messagingSenderId: '486206486627',
    projectId: 'bitcoin-cloud-mining-19fb5',
    storageBucket: 'bitcoin-cloud-mining-19fb5.firebasestorage.app',
    iosClientId: '486206486627-abcdefghijklmnop.apps.googleusercontent.com',
    iosBundleId: 'com.example.bitcoinCloudMining',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTBr5z9vixdO9TzzKVGCUVP-G4BaaMAyo',
    appId: '1:486206486627:ios:993fedd92937142473e056',
    messagingSenderId: '486206486627',
    projectId: 'bitcoin-cloud-mining-19fb5',
    storageBucket: 'bitcoin-cloud-mining-19fb5.firebasestorage.app',
    iosClientId: '486206486627-abcdefghijklmnop.apps.googleusercontent.com',
    iosBundleId: 'com.example.bitcoinCloudMining',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTBr5z9vixdO9TzzKVGCUVP-G4BaaMAyo',
    appId: '1:486206486627:web:993fedd92937142473e056',
    messagingSenderId: '486206486627',
    projectId: 'bitcoin-cloud-mining-19fb5',
    authDomain: 'bitcoin-cloud-mining-19fb5.firebaseapp.com',
    storageBucket: 'bitcoin-cloud-mining-19fb5.firebasestorage.app',
  );
}
